import { build } from 'esbuild'
import { readFile, writeFile, mkdir } from 'node:fs/promises'
import { fileURLToPath } from 'node:url'
import path from 'node:path'

const root = fileURLToPath(new URL('../', import.meta.url))
const publicDir = path.join(root, 'public')
const license = await readFile(path.join(root, 'LICENSE'), 'utf8')
await writeFile(path.join(publicDir, 'LICENSE.txt'), license)
const dependencyManifest = JSON.parse(await readFile(path.join(root, 'licenses/npm/SOURCES.json'), 'utf8'))
const noticesParts = ['Colors third-party notices\n\nColor names and RGB values: xkcd color survey, CC0.\nSource: https://xkcd.com/color/rgb.txt\nTerms: https://creativecommons.org/publicdomain/zero/1.0/\n']
for (const dependency of dependencyManifest) {
  noticesParts.push(`\n${dependency.package} ${dependency.version} (${dependency.license})\n`)
  for (const notice of dependency.notices) noticesParts.push(await readFile(path.join(root, notice), 'utf8'))
}
noticesParts.push('\nDM Sans 4.004, unmodified variable font\n', await readFile(path.join(publicDir, 'fonts/dmsans-OFL.txt'), 'utf8'))
await writeFile(path.join(publicDir, 'THIRD_PARTY_NOTICES.txt'), noticesParts.join('\n'))
await mkdir(path.join(publicDir, 'dist'), { recursive: true })
await mkdir(path.join(publicDir, 'vendor'), { recursive: true })
await mkdir(path.join(root, 'artifacts'), { recursive: true })
const app = await build({ entryPoints: [path.join(publicDir, 'app.js')], bundle: true, format: 'iife', target: ['es2022'], external: ['../vendor/supabase.js'], write: false, legalComments: 'inline' })
const script = app.outputFiles[0].text
await writeFile(path.join(publicDir, 'dist/app.js'), script)
await build({ stdin: { contents: "export { createClient } from '@supabase/supabase-js'", resolveDir: root }, bundle: true, format: 'esm', target: ['es2022'], outfile: path.join(publicDir, 'vendor/supabase.js'), legalComments: 'inline' })
let css = await readFile(path.join(publicDir, 'colors.css'), 'utf8')
const font = await readFile(path.join(publicDir, 'fonts/DMSans-Variable.ttf'))
css = css.replace('./fonts/DMSans-Variable.ttf', `data:font/ttf;base64,${font.toString('base64')}`)
const escape = (value) => value.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;')
const fontLicense = await readFile(path.join(publicDir, 'fonts/dmsans-OFL.txt'), 'utf8')
const notices = `<details id="offline-notices" class="offline-notices"><summary>Code, color data and font credits</summary><p>Color names and RGB values: xkcd color survey, CC0. Source: <a href="https://xkcd.com/color/rgb.txt">xkcd color list</a>. App curriculum ordering is generated by this project. DM Sans font is used unmodified under SIL OFL 1.1.</p><pre>${escape(license)}</pre><pre>${escape(fontLicense)}</pre></details>`
let html = await readFile(path.join(publicDir, 'index.html'), 'utf8')
html = html.replace('<link rel="stylesheet" href="./colors.css" />', `<style>${css}</style>`)
html = html.replace('href="./THIRD_PARTY_NOTICES.txt"', 'href="#offline-notices"')
html = html.replace('<script src="./dist/app.js" defer></script>', `<script>${script.replaceAll('</script', '<\\/script')}</script>`)
html = html.replace('</body>', `${notices}\n</body>`)
await writeFile(path.join(root, 'artifacts/Color-Learning.html'), html)
console.log('Built hosted app, optional local SDK bundle, and artifacts/Color-Learning.html.')
